[package]
name = "rfgui"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "rsx-macro",
    "lib/rfgui-components",
]

[dependencies]
wgpu = "28.0.0"
bytemuck = { version = "1.14", features = ["derive"] }
once_cell = "1.21.3"
glyphon = "0.10"
arboard = "3.6.1"
rfgui-rsx = { path = "rsx-macro" }

[lib]

[dev-dependencies]
winit = "0.30.12"
pollster = "0.3"
rfgui-components = { path = "lib/rfgui-components" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.1"
objc = "0.2"

[profile.dev]
opt-level = 1
